import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

import { Header } from './components/Header';
import { Footer } from './components/Footer';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});
const vollkorn = localFont({
    src: './fonts/Vollkorn-Regular.woff',
    variable: '--font-vollkorn',
    weight: '100 900',
});
const regencie = localFont({
    src: './fonts/RegencieLight.woff',
    variable: '--font-regencie',
    weight: '100 900',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${vollkorn.variable} ${regencie.variable} antialiased`}
            >
                <Header />
                <main>{children}</main>
            </body>
        </html>
    );
}
